name: Build and Push Docker Images

on:
  push:
    paths:
      - '**'
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Clear GitHub Actions cache
      #   run: |
      #     rm -rf ~/.cache/
      #     rm -rf ./.github/actions/

      - name: Checkout private actions
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.MY_GITHUB_USERNAME }}/${{ secrets.APP_NAME }}-actions
          ref: main
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: .github/actions
          clean: true
          fetch-depth: 0

      - name: Get Vault Secrets
        id: vault
        uses: ./.github/actions/.github/actions/vault-secrets
        with:
          vault_addr: "http://${{ secrets.DROPLET_IP }}:8200"
          droplet_ip: ${{ secrets.DROPLET_IP }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ steps.vault.outputs.dockerhub_username }}
          password: ${{ steps.vault.outputs.dockerhub_password }}

      - name: Build and push nginx
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ steps.vault.outputs.dockerhub_username }}/${{ steps.vault.outputs.app_name }}-nginx:latest
            ${{ steps.vault.outputs.dockerhub_username }}/${{ steps.vault.outputs.app_name }}-nginx:${{ github.sha }}

      - name: Trigger Deploy workflow in DevOps
        if: success() # only runs if previous steps succeeded
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPO_ACCESS_TOKEN }}" \
            https://api.github.com/repos/${{ secrets.MY_GITHUB_USERNAME }}/${{ steps.vault.outputs.app_name }}-devops/dispatches \
            -d '{"event_type": "nginx-updated", "client_payload": {"customData": "value"}}'