# The AllCops section applies settings globally.
AllCops:
  Exclude:
    - 'db/schema.rb' # Exclude schema file from linting.
    - 'bin/*'
    - 'config/**/*'
    - 'spec/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'coverage/**/*'
    - 'Gemfile'
    - 'Gemfile.lock'
    
  TargetRubyVersion: 3.3.1 # Set the target Ruby version for your project.
  NewCops: enable

# Style settings for different cops (Style, Layout, etc.)
Layout/LineLength:
  Max: 100 # Set max line length to 100 characters.

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb' # Exclude spec files from block length cop.

# Enable or disable specific cops.
Lint/UnusedMethodArgument:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true

# Define settings for Rails projects using rubocop-rails.
require: rubocop-rails

Rails/SkipsModelValidations:
  Enabled: true

# Configure new cops
Gemspec/DeprecatedAttributeAssignment:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: single_quotes