name: Deploy to Digital Ocean

on:
  repository_dispatch:
    types: [nginx-updated, frontend-updated, backend-updated]
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Vault
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DROPLET_IP: ${{ secrets.DROPLET_IP }}
        run: |
          chmod +x deploy-vault.sh
          ./deploy-vault.sh

      - name: Deploy Services
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DROPLET_IP: ${{ secrets.DROPLET_IP }}
        run: |
          chmod +x deploy-services.sh
          ./deploy-services.sh
